services:
  fritzboxmonitor:
    image: chrismkv/fritzboxmonitor:latest
    container_name: fritzboxmonitor
    environment:
      - FRITZBOX_IP=192.168.0.1
      - FRITZBOX_USER=Username
      - FRITZBOX_PASSWORD=Password
    network_mode: synobridge
    restart: unless-stopped